import fs from "fs";
import path from "path";
import Head from "next/head";
import matter from "gray-matter";
import Post from "../components/Post";
import { sortByDate } from "../utils";
import { BlogContainer, BlogPostsContainer } from "../styles/Blog.styled.js";

export default function Home({ posts }) {
  return (
    <BlogContainer>
      <Head>
        <title>Books</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Books 2021</h1>
      <BlogPostsContainer>
        {posts.map((post, index) => (
          <Post key={index} post={post} />
        ))}
      </BlogPostsContainer>
    </BlogContainer>
  );
}

export async function getStaticProps() {
  const files = fs.readdirSync(path.join("posts"));

  const posts = files.map((filename) => {
    const slug = filename.replace(".md", " ");
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });
  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  };
}
